language: node_js
node_js:
  - node
before_install:
  - npm install -g npm@latest
cache: npm
install:
  - npm install jest
  - npm install coveralls
script:
  - npm test

script: echo "Running tests against $(node -v)..."

jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage


addons:
  artifacts:
    s3_region: "eu-central-1" # defaults to "us-east-1"
