language: node_js
node_js:
  - node
before_install:
  - npm install -g npm@latest
cache: npm
install:
  - npm install jest
  - npm install coveralls
script:
  - npm test


jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js


addons:
  artifacts:
    s3_region: "us-east-1"
    target_paths:
    - /travis/
    debug: true
    paths:
      - ./coverage